import { images } from "../../constants";

const exportedObject = [
    {
        id: 1,
        title: "Web Development",
        description: "I am a good web developer",
        imgUrl: images.about01,
        projectLink: "https://github.com/Phraewkwan",
        category: "React JS",
      },
      {
        id: 2,
        title: "Front-end Development",
        description: "I am a good web developer",
        imgUrl: images.about02,
        projectLink: "https://github.com/Phraewkwan",
        category: "Web App",
      },
      {
        id: 3,
        title: "Web Design",
        description: "I am a good web developer",
        imgUrl: images.about03,
        category: "React JS",
      },
      {
        id: 4,
        title: "UX/UI",
        description: "I am a good web developer",
        imgUrl: images.about04,
        projectLink: "https://github.com/Phraewkwan",
        category: "UX/UI",
      },
      {
        id: 5,
        title: "YouTube Clone UI",
        description: "Clone UI of YouTube",
        imgUrl: images.youtube,
        projectLink: "https://youtube-cloneui.netlify.app/",
        projectLinkGithub: "https://github.com/Phraewkwan/YouTube_cloneUI",
        category: "Web App",
      },
      {
        id: 6,
        title: "Dashboard For E-commerce",
        description: "Dashbord for small e-commerce business",
        imgUrl: images.dashboard,
        projectLink: "https://dashboard-for-shop.netlify.app/",
        projectLinkGithub: "",
        category: "Web App",
      },
      {
        id: 7,
        title: "Weather App",
        description: "App for checking the climate",
        imgUrl: images.about02,
        projectLink: "https://github.com/Phraewkwan",
        projectLinkGithub: "https://github.com/Phraewkwan/weather-app",
        category: "Mobile App",
      },
      {
        id: 8,
        title: "Fit Club Web application",
        description: "Web application for health business",
        imgUrl: images.fitclub,
        projectLink: "https://fitclub-007.netlify.app/",
        projectLinkGithub: "",
        category: "Web App",
      },
      {
        id: 9,
        title: "Photo editing by photoshop & lightroom",
        description: "Customize hotel pictures for Facebook Fanpage",
        imgUrl: images.khanom,
        projectLink: "https://drive.google.com/drive/folders/12lgW41gTSlWh32qi8AJAg64Hyt5i7FIt?fbclid=IwAR0-3LeDIHIsYITwwoupXplE3qHtMcNHUgF6RuYp2eexMmPJg0RNzlcyOZQ",
        projectLinkGithub: "",
        category: "Graphic Design",
      },
      {
        id: 10,
        title: "Photo editing by photoshop & lightroom",
        description: "Customize hotel pictures",
        imgUrl: images.pai,
        projectLink: "https://drive.google.com/drive/folders/1Et7BiIqhA-OoSxiQJUkyXmQ2f9AMImY-?fbclid=IwAR0-3LeDIHIsYITwwoupXplE3qHtMcNHUgF6RuYp2eexMmPJg0RNzlcyOZQ",
        projectLinkGithub: "",
        category: "Graphic Design",
      },
      {
        id: 11,
        title: "Photo editing by photoshop & lightroom",
        description: "Customize hotel pictures",
        imgUrl: images.khanombar,
        projectLink: "https://drive.google.com/drive/folders/1gV7KPudF0zhtdBWlUk94OBXDSFjDicDS?fbclid=IwAR0-3LeDIHIsYITwwoupXplE3qHtMcNHUgF6RuYp2eexMmPJg0RNzlcyOZQ",
        projectLinkGithub: "",
        category: "Graphic Design",
      },
      {
        id: 12,
        title: "Booking clone website",
        description: "clone UI (the project is still running)",
        imgUrl: images.booking,
        projectLink: "https://booking-clone-site.netlify.app/",
        projectLinkGithub: "",
        category: "React JS",
      },
      {
        id: 13,
        title: "Oli Blog",
        description: "FullStack Blog Site (the project is still running)",
        imgUrl: images.oliblog,
        projectLink: "https://oli-blog.netlify.app/",
        projectLinkGithub: "https://github.com/Phraewkwan/Oli-Blog",
        category: "React JS",
      },
]

export default exportedObject;